# inventory-test.ini
[servers-zcast]
zcast-vesco-8-columbus.tail4452a9.ts.net
zignage-player-023004.tail4452a9.ts.net
zcast-vesco-14-dayton.tail4452a9.ts.net
vesco-4-sf-ar-0230044.tail4452a9.ts.net
sfmainfloor-0230043.tail4452a9.ts.net
vesco-1-gr-starr.tail4452a9.ts.net
zcast-vesco-15-wauseon.tail4452a9.ts.net
zcast-vesco-3-medina.tail4452a9.ts.net
[servers-zcast:vars]
ansible_user = zignage
ansible_ssh_pass = zignage
ansible_become_pass = zignage
[zplayers_prod]
100.104.60.96
[zplayers_prod:vars]
ansible_user = zignage
ansible_ssh_pass = The_Z1GN06e_W3stFi3ld_player%45
ansible_become_pass = The_Z1GN06e_W3stFi3ld_player%45
ansible_python_interpreter = /home/zignage/.pyenv/versions/3.11.2/bin/python
