- name: Check LUKS container on /dev/nvme0n1p8
  shell: |
    cryptsetup isLuks /dev/nvme0n1p8 || true
  args:
    executable: /bin/bash
  register: luks_check

- name: Format LUKS container if unformatted
  shell: |
    echo -n "{{ luks_passphrase }}" | cryptsetup luksFormat /dev/nvme0n1p8 -
  args:
    executable: /bin/bash
  when: luks_check.rc != 0  # Ensure this runs when NOT LUKS-formatted

#- name: Check if LUKS container is open
##  stat:
 ##   path: /dev/mapper/nvme_crypt
  #register: luks_open_check

- name: Open LUKS container
  community.crypto.luks_device:
    device: /dev/nvme0n1p8
    state: opened
    passphrase: "{{ luks_passphrase }}"
    name: nvme_crypt
    persistent: yes
    allow_discards: yes

