- name: Check LUKS container on /dev/nvme0n1p8
  shell: |
    cryptsetup isLuks /dev/nvme0n1p8 || true
  args:
    executable: /bin/bash
  register: luks_check

- name: Format LUKS container if unformatted
  shell: |
    echo -n "{{ luks_passphrase }}" | sudo cryptsetup luksFormat /dev/nvme0n1p8 -
  args:
    executable: /bin/bash
  when: luks_check.rc != 0

- name: Check if LUKS container is open
  stat:
    path: /dev/mapper/nvme_crypt
  register: luks_open_check

- name: Open LUKS container if closed
  shell: |
    echo -n "{{ luks_passphrase }}" | sudo cryptsetup open /dev/nvme0n1p8 nvme_crypt -
  args:
    executable: /bin/bash
  when: not luks_open_check.stat.exists
