- name: Check existing partition /dev/nvme0n1p8 exists.
  stat:
    path: /dev/nvme0n1p8
  register: p8_check

- name: Create partition if missing
  shell: |
    parted --script /dev/nvme0n1 mkpart primary ext4 180GB 100%
    partprobe /dev/nvme0n1 && sleep 5
  args:
    executable: /bin/bash
  when: not p8_check.stat.exists

- name: Verify partition existence post-creation
  stat:
    path: /dev/nvme0n1p8
  register: p8_check_post

- name: Reboot if partition missing
  reboot:
    reboot_timeout: 600
  when: not p8_check_post.stat.exists

- name: Fail if partition not created
  fail:
    msg: "Partition /dev/nvme0n1p8 was not created!"
  when: not p8_check_post.stat.exists
